CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(11) UNIQUE,
    password VARCHAR(64) NOT NULL,
    role VARCHAR(32) DEFAULT 'USER',
    is_deleted BOOLEAN DEFAULT FALSE
)
